import {freshDemo} from '../data/demo.mjs';
import {LAYERS,LABELS,COLORS,PALACES,selectPeriod,optionsFor,filterMemories,traceMemory,sharedAxes,appendFeedback} from './memory.mjs';
let archive=freshDemo(),profileId='sample-a',selection={},palace=null,activeId='m-01',query='';
const $=s=>document.querySelector(s);
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const period=id=>archive.periods.find(p=>p.id===id);
function active(){return traceMemory(archive,activeId,profileId);}
function getVisible(){return filterMemories(archive,{profileId,selection,palace,query});}
function chooseRecord(id,loadPath=false){activeId=id;const record=active()?.record;if(loadPath&&record){selection=Object.fromEntries(record.tags.slice(1).map(t=>[t.layer,t.periodId]));palace=null;query='';}render();}
function notify(message){$('#status').textContent=message;}
function chart(record){
 const tags=record?.tags||[],visible=tags.filter(t=>t.layer==='natal'||selection[t.layer]);
 const positions=PALACES.map((name,i)=>{const a=(i*30-90)*Math.PI/180;return {name,x:260+192*Math.cos(a),y:260+192*Math.sin(a)};});
 const links=visible.map(t=>positions.find(p=>p.name===t.anchorPalace));
 return `<svg class="chart" viewBox="0 0 520 520" aria-label="归档宫位标签地图，点击宫位可筛选记忆"><defs><radialGradient id="halo"><stop stop-color="#e9efff"/><stop offset="1" stop-color="#f9fbff" stop-opacity="0"/></radialGradient></defs><circle cx="260" cy="260" r="178" fill="url(#halo)"/><g fill="none" stroke="#dfe6f0"><circle cx="260" cy="260" r="148"/><circle cx="260" cy="260" r="194" stroke-dasharray="2 9"/><ellipse cx="260" cy="260" rx="120" ry="48" transform="rotate(-32 260 260)"/><ellipse cx="260" cy="260" rx="120" ry="48" transform="rotate(50 260 260)"/></g>
 ${links.map((p,i)=>`<path d="M260 260 Q${260+(p.x-260)*.35} ${260+(p.y-260)*.6} ${p.x} ${p.y}" fill="none" stroke="${COLORS[visible[i].layer]}" stroke-width="1.6" stroke-dasharray="4 6" opacity=".55"/>`).join('')}
 <circle cx="260" cy="260" r="54" fill="#fff" stroke="#d9e3f4"/><text x="260" y="257" text-anchor="middle" class="chart-center">${visible.length} LAYERS</text><text x="260" y="279" text-anchor="middle" class="chart-caption">归档时的结构</text>
 ${positions.map(p=>{const matches=visible.filter(t=>t.anchorPalace===p.name),selected=palace===p.name;return `<g class="palace ${matches.length?'lit':''} ${selected?'selected':''}" role="button" tabindex="0" aria-label="筛选${p.name}" aria-pressed="${selected}" data-palace="${p.name}" transform="translate(${p.x} ${p.y})"><rect x="-30" y="-25" width="60" height="50" rx="15"/><text text-anchor="middle" y="0">${p.name}</text>${matches.map((t,i)=>`<circle cx="${(i-(matches.length-1)/2)*7}" cy="13" r="2.5" fill="${COLORS[t.layer]}"/>`).join('')}</g>`;}).join('')}</svg>`;
}
function render(){
 const visible=getVisible();if(!visible.some(r=>r.id===activeId))activeId=visible[0]?.id||'';
 const trace=active(),record=trace?.record,natal=archive.periods.find(p=>p.layer==='natal'&&p.profileId===profileId);
 $('#app').innerHTML=`<header class="topbar"><a class="brand" href="./"><img src="./docs/mark.svg" width="30" height="30" alt=""/><strong>Xytha</strong><span>MEMORY ATLAS</span></a><nav><a href="./docs/architecture.html">设计说明 ↗</a><a href="https://xytha.com" target="_blank" rel="noopener noreferrer" class="product-link">体验 Xytha ↗</a></nav></header>
 <main><section class="hero"><div><p class="eyebrow"><span class="pulse"></span> OPEN EXPLORATION / 001</p><h1>Memory, with a map.</h1><p class="intro">让每条记忆，都有可追溯的坐标。</p><p class="description">从原始表达出发，以六层时间与宫位叠加组织记忆。<br>看见关联，回到来源，让后续反馈留下痕迹。</p></div><aside class="hero-note"><b>可检查，而非黑箱</b><span>六层时间 → 归档标签 → 来源原文</span><button id="walkthrough">查看六层示例 <span>↗</span></button></aside></section>
 <div class="notice"><span class="dot"></span>全部为合成角色、对话与标签。此处展示索引结构，不进行排盘，也不证明命理标签能预测偏好。</div>
 <section class="workbench" aria-label="记忆工作台"><div class="bench-head"><div><span class="eyebrow">EXPLORE THE ARCHIVE</span><h2>记忆图谱</h2></div><div class="bench-actions"><label class="sr-only" for="profile">切换示例角色</label><select id="profile">${archive.profiles.map(p=>`<option value="${p.id}" ${p.id===profileId?'selected':''}>${esc(p.name)}</option>`).join('')}</select><button id="reset">重置筛选</button></div></div>
 <div class="time-stack" aria-label="六层时间选择"><div class="time-row"><b>本命</b><span class="time-chip fixed" style="--layer:${COLORS.natal}">${natal.stemBranch} <small>固定背景</small></span><span class="time-help">逐层选择 · 再点取消 · 上级改变时清空下级</span></div>${LAYERS.slice(1).map(layer=>{const options=optionsFor(archive,profileId,selection,layer);return `<div class="time-row"><b>${LABELS[layer]}</b><div class="time-options">${options.length?options.map(p=>`<button class="time-chip" style="--layer:${COLORS[layer]}" aria-pressed="${selection[layer]===p.id}" data-time="${p.id}">${p.stemBranch}<small>${esc(p.label)}</small></button>`).join(''):`<span class="muted">先选择${LABELS[LAYERS[LAYERS.indexOf(layer)-1]]}</span>`}</div></div>`;}).join('')}</div>
 <div class="atlas-grid"><section class="map-panel"><div class="panel-caption"><span>01 / PALACE MAP</span><small>${palace?`筛选：${palace}`:'点击宫位，查看相关记忆'}</small></div>${chart(record)}<div class="legend">${LAYERS.map(layer=>`<span><i style="background:${COLORS[layer]}"></i>${LABELS[layer]}</span>`).join('')}</div><p class="map-foot">连线来自当前记忆的归档标签。<br>切换时间只筛选已有记录，不重写历史标签。</p></section>
 <section class="records-panel"><div class="panel-caption"><span>02 / MEMORY INDEX</span><small>${visible.length} 条匹配</small></div><label class="sr-only" for="search">搜索示例记忆</label><input id="search" type="search" value="${esc(query)}" placeholder="搜索原话或概述…" maxlength="200"/>
 <div class="record-list">${visible.map(r=>`<button class="record-card ${r.id===activeId?'active':''}" data-record="${r.id}" aria-pressed="${r.id===activeId}"><span class="record-meta">${r.recordedAt.slice(0,10)}<span>${r.tags.length} 层标签</span></span><b>${esc(r.summary)}</b><span class="quote-preview">“${esc(r.quote)}”</span><span class="record-axis">${sharedAxes(r.tags).map(a=>a.palaces.join(' · ')).join(' / ')} <span>↗</span></span></button>`).join('')||'<div class="empty">没有匹配的合成记录。<br>可以取消宫位或时间筛选。</div>'}</div></section>
 <section class="source-panel"><div class="panel-caption"><span>03 / SOURCE TRACE</span><small>${record?esc(record.id):'—'}</small></div>${trace?`<span class="pill">合成示例 · 可追溯</span><h3>从整理后的记忆，回到原话。</h3><div class="summary-block"><span class="eyebrow">压缩概述</span><p>${esc(record.summary)}</p><small>人工编写的演示概述，非模型评测结果。</small></div><details class="source" open><summary>原始对话 <span>${esc(trace.source.id)}</span></summary><p class="speaker">用户 · ${trace.source.at.slice(0,10)}</p><p>${esc(trace.source.question)}</p><p class="speaker">示例回复</p><p>${esc(trace.source.answer)}</p></details>
 <details class="tags-detail" open><summary>归档标签 <span>6 LAYERS</span></summary><div class="tag-list">${record.tags.map(tag=>`<div><span class="layer-badge" style="--layer:${COLORS[tag.layer]}">${LABELS[tag.layer]}</span><code>${tag.stemBranch}</code><span>${tag.palace} → 本命${tag.anchorPalace}</span></div>`).join('')}</div></details>
 <section class="feedback"><b>这条整理符合你的表达吗？</b><p>反馈独立追加，原文与标签保持不变。</p><div><button data-feedback="useful">符合</button><button data-feedback="not-relevant">不适用</button><button id="correction-toggle">补充更正</button></div><form id="correction-form" hidden><label for="correction">更正说明（仅本页演示）</label><textarea id="correction" maxlength="500" required placeholder="例如：只在职业讨论中适用，不是固定偏好。"></textarea><button type="submit">记录更正</button></form><ul>${trace.feedback.map(f=>`<li>${({useful:'确认符合','not-relevant':'标记不适用',correction:'补充更正'})[f.kind]}${f.note?'：'+esc(f.note):''}</li>`).join('')}</ul></section>`:'<div class="empty">选择一条记忆，查看原始对话与归档标签。</div>'}</section></div>
 <div class="bench-foot"><span>运行于浏览器当前页面 · 刷新即重置 · 无模型调用</span><button id="export">导出示例 JSON ↓</button></div></section>
 <section class="closing"><div><p class="eyebrow">FROM STRUCTURE TO EXPERIENCE</p><h2>这是结构的起点。<br>完整的体验，在 Xytha。</h2></div><a href="https://xytha.com" target="_blank" rel="noopener noreferrer">试试 Xytha ↗</a></section></main><footer><span>© 2026 Xytha Memory Atlas contributors</span><span>0.1.0 · MIT · Synthetic examples</span></footer><p id="status" class="sr-only" role="status" aria-live="polite"></p>`;
 $('#profile').onchange=e=>{profileId=e.target.value;selection={};palace=null;query='';activeId='';render();};
 $('#reset').onclick=()=>{selection={};palace=null;query='';render();};
 $('#walkthrough').onclick=()=>{const r=archive.records.find(r=>r.profileId===profileId);chooseRecord(r.id,true);$('.workbench').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
 document.querySelectorAll('[data-time]').forEach(button=>button.onclick=()=>{selection=selectPeriod(selection,button.dataset.time,archive,profileId);render();});
 document.querySelectorAll('[data-palace]').forEach(button=>{const pick=()=>{palace=palace===button.dataset.palace?null:button.dataset.palace;render();};button.onclick=pick;button.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick();}};});
 document.querySelectorAll('[data-record]').forEach(button=>button.onclick=()=>chooseRecord(button.dataset.record));
 $('#search').oninput=e=>{const position=e.target.selectionStart;query=e.target.value;render();$('#search').focus();try{$('#search').setSelectionRange(position,position);}catch{}};
 document.querySelectorAll('[data-feedback]').forEach(button=>button.onclick=()=>feedback(button.dataset.feedback));
 if($('#correction-toggle')){$('#correction-toggle').onclick=()=>{$('#correction-form').hidden=!$('#correction-form').hidden;if(!$('#correction-form').hidden)$('#correction').focus();};$('#correction-form').onsubmit=e=>{e.preventDefault();const note=$('#correction').value.trim();if(note)feedback('correction',note);};}
 $('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(archive,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='xytha-memory-atlas.synthetic.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('已导出示例数据，包含本页主动填写的反馈。');};
}
function feedback(kind,note=''){archive=appendFeedback(archive,{id:crypto.randomUUID(),recordId:activeId,profileId,kind,note,at:new Date().toISOString().replace(/\.\d{3}Z$/,'Z')});render();notify('已追加反馈，归档内容保持不变。');}
render();
